---
##############################################################################
#
# handlers file for dockersvc
#
##############################################################################
- name:     'Systemd daemon-reload'
  command:  'systemctl daemon-reload'
- name:      'Ensure service state'
  service:
    name:    "{{dockersvc_conf.name}}"
    enable:  "{{dockersvc_conf.ensure.enable|default(omit)}}"
    state:   "{{dockersvc_conf.ensure.state|default(omit)}}"
  when:  __ensure_service == True
